Rails:
 Enabled: true

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
